import { Inter,Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '700', '800', '900' ]
});

export const metadata = {
  title: "Leí Pinheiro - Portfólio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
